---
- name: Connectivity & Failover Ping Tests 
  hosts: cisco
  gather_facts: no

  vars:
    ping_targets:
      - name: VLAN67 Gateway
        ip: 192.168.67.254
      - name: VLAN69 Gateway
        ip: 192.168.69.254
      - name: VLAN99 Gateway
        ip: 192.168.99.254
      - name: ISP Loopback
        ip: 21.25.67.69
      - name: AWS EC2
        ip: 54.91.226.48
      - name: Chris PC
        ip: 192.168.69.11
      - name: AAA_server/syslog
        ip: 192.168.67.13
      - name: ISP
        ip: 192.168.1.1
        

  tasks:

    - name: Run ping tests from distribution switches only
      ios_command:
        commands:
          - ping {{ item.ip }} repeat 15
      loop: "{{ ping_targets }}"
      register: ping_results
      ignore_errors: yes

    - name: Display ping results
      debug:
        msg:
          - "===== {{ inventory_hostname }} → {{ item.item.name }} ====="
          - "{{ item.stdout }}"
      loop: "{{ ping_results.results }}"
      when: ping_results is defined
